#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Respect the shebang and mark file as executable

import os
import random
from flask import Flask
from waitress import serve

# create and configure the app
app = Flask(__name__, instance_relative_config=True)
app.config.from_mapping(
    SECRET_KEY=random.randbytes(128)
)
# ensure the instance folder exists
try:
    os.makedirs(app.instance_path)
except OSError:
    pass

@app.route('/')
def index():
    print("Log something", flush=True) # flush=True is required for printing in flask applications 
    return 'Hello, World!'

@app.route('/flag')
def hello():
    with open("/flag.txt") as f:
        return f.read()


serve(app, host='0.0.0.0', port=1337)
